apiVersion: v1
kind: Service
metadata:
  name: backend-nginx-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: {{ template "cortex-helm.name" . }}-backend
  ports:
      - protocol: TCP
        port: 80
        targetPort: 8080
