apiVersion: v1
kind: Service
metadata:
  name: nginx-service-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: {{ template "cortex-helm.name" . }}-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
