apiVersion: v1
kind: Service
metadata:
  name: frontend-nginx-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: {{ template "cortex-helm.name" . }}-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
