apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cortex-helm.name" . }}-deployment-frontend
  labels:
    app: {{ template "cortex-helm.name" . }}-frontend
spec:
  selector:
    matchLabels:
      app: {{ template "cortex-helm.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ template "cortex-helm.name" . }}-frontend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/frontend/configmap.yaml") . | sha256sum }}
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 10 }}
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: "ghcr.io/cortexapps/brain-app/cortex-onprem-frontend:{{.Values.image.version}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.frontend.nginx.port }}
          env:
            - name: NGINX_PORT
              value: "{{ .Values.app.frontend.nginx.port }}"
          volumeMounts:
            - name:  frontend-config-volume
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
              readOnly: true
      volumes:
        - name: frontend-config-volume
          configMap:
            name: {{ template "cortex-helm.name" . }}-deployment-frontend-configmap
