apiVersion: v1
kind: Service
metadata:
  name: {{ template "cortex-helm.fullname" . }}-backend-service
spec:
  selector:
    app: {{ template "cortex-helm.name" . }}-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080